-- Database: LOINC

-- DROP DATABASE "LOINC";

CREATE DATABASE "LOINC"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
    
    
    CREATE TABLE loinc_core (
	NUM INTEGER NOT NULL PRIMARY KEY,
	COMPONENT VARCHAR NOT NULL,
	PROPERTY VARCHAR NOT NULL,
	TIME_ASCPECT VARCHAR NOT NULL,
	SYSTEM_INFORMATION VARCHAR NOT NULL,
	SCALE_TYPE VARCHAR NOT NULL,
	METHOD_TYPE VARCHAR,
	CLASS_INFORMATION VARCHAR NOT NULL,
	CLASS_TYPE INTEGER NOT NULL,
	LONG_NAME VARCHAR NOT NULL,
	SHORT_NAME VARCHAR NOT NULL,
	EXTERNAL_COPYRIGHT_NOTICE VARCHAR NOT NULL,
	STATUS VARCHAR NOT NULL,
	VERSION_FIRST_RELEASED VARCHAR NOT NULL,
	VERSION_LAST_CHANGED VARCHAR NOT NULL);